import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/layout/Header";
import Footer from "@/layout/Footer";
import Head from "next/head";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Requlin-OPC-Private-Limited",
  description: "Generated by create next app",
  icons: {
    icon: "/src/assets/logo.png", // /public path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {" "}
        <Head>
          <link rel="icon" href="/src/assets/logo.png" />
          {/* Add other meta tags or favicons if needed */}
        </Head>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
